# Generated by Django 2.0.6 on 2020-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcast', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('album_id', models.CharField(blank=True, max_length=36, null=True)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
