# Generated by Django 2.0.6 on 2020-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0002_remove_chapter_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='create_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='publish_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
