# Generated by Django 2.0.6 on 2020-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrticle',
            name='create_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mrticle',
            name='publish_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
